[package]
name = "tocat-plugin-rate"
version.workspace = true
edition.workspace = true
description = "tocat plugin that measures and reports throughput"
repository.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
tocat-api = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
