[package]
name = "tocat-plugin-timeout"
version.workspace = true
edition.workspace = true
description = "tocat plugin that ends stream after a period of inactivity"
repository.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tocat-api = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
