[package]
name = "tocat-plugin-compress"
version.workspace = true
edition.workspace = true
description = "tocat plugin that provides (de)compression stages"
repository.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
tocat-api = { workspace = true }
zstd = "0.13.3"

[dev-dependencies]
serde_json = { workspace = true }
