[workspace]
resolver = "3"
members = ["crates/tocat-api", "crates/tocat-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lkalir/tocat"

[workspace.dependencies]
tocat-api = { path = "crates/tocat-api" }

[profile.release]
debug = 1
