[workspace]
resolver = "3"
members = [
  "crates/tocat-api",
  "crates/tocat-cli",
  "crates/tocat-plugins",
  "crates/tocat-wasm-abi",
  "crates/tocat-wasm-sdk",
  "crates/tocat-wasm-shell"
]
exclude = ["examples/"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.94.1"
repository = "https://github.com/lkalir/tocat"
license = "MIT OR Apache-2.0"
keywords = ["netcat", "proxy", "relay", "socat", "tcp"]

[workspace.dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tocat-api = { path = "crates/tocat-api", version = "0.2.0" }
tocat-wasm-abi = { path = "crates/tocat-wasm-abi", version = "0.2.0" }
wasmtime = "47.0.3"

[workspace.dependencies.tocat-plugins]
path = "crates/tocat-plugins"
version = "0.2.0"
default-features = false

[profile.ci]
inherits = "dev"
opt-level = 1
