//! toupper - upper-case the stream.
//!
//! The smallest useful guest: one transform per chunk, no state, no options.
//!
//!     tocat - 'wasm,module=toupper.wasm' tcp:localhost:9000
//!
//! Everything the host looks for is generated by `export_guest!`: the arena,
//! the outbox, the panic handler, and the nine exports. What is written here
//! is the transform and two facts about it.

#![no_std]

use tocat_wasm_sdk::{Boundaries, Context, Guest, export_guest};

/// The most a chunk may be, which has to be at or above the relay's copy
/// buffer (256 KiB by default) or the relay has to be run with a matching
/// `-b`. A larger chunk is refused, and refusing fails that direction.
const CAPACITY: usize = 256 * 1024;

pub struct ToUpper {
    /// The host reads what we emit after the call returns, so the output
    /// cannot be a local.
    out: [u8; CAPACITY],
}

impl Guest for ToUpper {
    /// Built at compile time: nothing calls `__wasm_call_ctors` in a module
    /// built with `--no-entry`, so a guest constructed at run time would never
    /// be constructed at all.
    const INIT: Self = Self { out: [0; CAPACITY] };

    /// One message in, one message out, and nothing is held across calls, so
    /// this preserves boundaries. A guest that says nothing claims nothing,
    /// which is the right default and the wrong answer here.
    const BOUNDARIES: Boundaries = Boundaries::Preserve;

    fn on_bytes(&mut self, ctx: &mut Context, input: &[u8]) {
        for (out, byte) in self.out.iter_mut().zip(input) {
            *out = byte.to_ascii_uppercase();
        }

        // One emission, so one unit: one write at a byte sink, one datagram at
        // a datagram sink. No boundaries are needed to say that.
        ctx.emit(&self.out[..input.len()]);
    }
}

export_guest!(ToUpper, arena_bytes = CAPACITY);
