[package]
name = "tocat-plugin-tee"
version.workspace = true
edition.workspace = true
description = "tocat plugin that mirrors data to a side channel"
repository.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tocat-api = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
