[package]
name = "tocat-plugin-process"
version.workspace = true
edition.workspace = true
description = "tocat plugin that uses a subprocess to transform data"
repository.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tocat-api = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
