[package]
name = "tocat-plugins"
version.workspace = true
edition.workspace = true
description = "Built-in tocat plugins"
repository.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
tocat-api = { path = "../tocat-api", version = "0.1.0" }
tocat-wasm-abi = { workspace = true, optional = true }
wasmtime = { workspace = true, optional = true }
zstd = { version = "0.13.3", optional = true }

[features]
default = [
  "block",
  "compress",
  "limit",
  "process",
  "rate",
  "tee",
  "throttle",
  "timeout",
  "wasm"
]
block = []
compress = ["dep:zstd"]
limit = []
process = []
rate = []
tee = []
throttle = []
timeout = []
wasm = ["dep:serde_json", "dep:tocat-wasm-abi", "dep:wasmtime"]
